services:
  - type: web
    name: academy-app
    env: php
    region: frankfurt
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan optimize
      php artisan migrate --force
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: academy-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: academy-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: academy-db
          property: name
      - key: DB_USERNAME
        fromDatabase:
          name: academy-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: academy-db
          property: password
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false

databases:
  - name: academy-db
    databaseName: academy_db
    user: academy_user
    ipAllowList: [] 